previewsEnabled: true
services:
  # A Docker web service
  - type: web
    name: website
    env: node
    region: oregon
    plan: standard
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: node build/index.js
    pullRequestPreviewsEnabled: true
    initialDeployHook: npx prisma db seed
    buildFilter:
      paths:
        - src/**/*.svelte
        - src/**/*.ts
        - src/**/*.html
      ignoredPaths:
        - src/**/*.test.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_LOGIN
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: BASE_URL
        value: https://www.octopuzzles.com
        previewValue: REPLACE_ME
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: database
    databaseName: octopuzzles
    user: octopuzzles
    ipAllowList: []
